In [ ]:
Hafta2- Ders2 Numpy

In [1]:
pip install numpy

In [2]:
import numpy as np

In [3]:
liste1 = [1, 2, 3, 4, 5, 6]

dizi1 = np.array(liste1)

print("liste", type(liste1))
print("np dizisi", type(dizi1))

print(dizi1)

liste <class 'list'>
np dizisi <class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [4]:
print("Veri türü (dtype):", dizi1.dtype)

Veri türü (dtype): int64


In [5]:
print("Boyut (shape):", dizi1.shape)

Boyut (shape): (6,)


In [6]:
liste2 = [
    [80, 90, 70],
    [20, 50, 60],
    [56, 67, 90]
]

dizi2 = np.array(liste2)

print(dizi2)
print(dizi2.shape)

[[80 90 70]
 [20 50 60]
 [56 67 90]]
(3, 3)


In [7]:
sifirlar_dizisi = np.zeros(5)

sifirlar_dizisi

array([0., 0., 0., 0., 0.])

In [8]:
sifirlar_dizisi2 = np.zeros((5, 3))
sifirlar_dizisi2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
birler_dizisi = np.ones((5, 2))
birler_dizisi

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
print("boyut sayısı", birler_dizisi.ndim)
print("boyut şekli", birler_dizisi.shape)

boyut sayısı 2
boyut şekli (5, 2)


In [11]:
birler_dizisi.size

10